#RunshellScript
#RunPowerShellScript

trigger:
- none

pool:
  vmImage: ubuntu-latest
  
variables:
  -name: vm_name
  -value: "myVM"
  -name: rg_name
  value: "myResourceGroup"
  
  
steps


- task: AzureCLI@2
      displayName: execute command inside vm
      inputs:
        azureSubscription: 'subscription'
        scriptType: 'ps'
        scriptLocation: 'inlineScript'
        inlineScript: 'az vm run-command invoke --command-id RunPowerShellScript --name $(vm_name) -g $(vnet_rg_name) --scripts "hostname"'
